/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_a7_24ndktest_JNIUtils */

#ifndef _Included_com_example_a7_24ndktest_JNIUtils
#define _Included_com_example_a7_24ndktest_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_a7_24ndktest_JNIUtils
 * Method:    calculate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_a7_124ndktest_JNIUtils_calculate
        (JNIEnv * env, jobject object, jint x, jint y){
    return x+y;
};

#ifdef __cplusplus
}
#endif
#endif
